// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS_TXLzr7c9FbaSt6T9uOBl-V-rqBGNx0',
    appId: '1:961625405654:web:17112abef06af704d1f177',
    messagingSenderId: '961625405654',
    projectId: 'esp32-firebase-48836',
    authDomain: 'esp32-firebase-48836.firebaseapp.com',
    databaseURL:
        'https://esp32-firebase-48836-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-firebase-48836.appspot.com',
    measurementId: 'G-ZVWJHMJ02W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLWkVBbOOf3Al3t8eX-UXAuwGd_loJQfs',
    appId: '1:961625405654:android:e66fb5bb198ea57bd1f177',
    messagingSenderId: '961625405654',
    projectId: 'esp32-firebase-48836',
    databaseURL:
        'https://esp32-firebase-48836-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'esp32-firebase-48836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfxONfVbXgx24zgwWWHRr7oEF0MkjT-MQ',
    appId: '1:961625405654:ios:f805a420bff71d93d1f177',
    messagingSenderId: '961625405654',
    projectId: 'esp32-firebase-48836',
    databaseURL:
        'https://esp32-firebase-48836-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-firebase-48836.appspot.com',
    iosClientId:
        '961625405654-5lankhto02dgm2fflas8g7g1marki2ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.gabusBuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfxONfVbXgx24zgwWWHRr7oEF0MkjT-MQ',
    appId: '1:961625405654:ios:f805a420bff71d93d1f177',
    messagingSenderId: '961625405654',
    projectId: 'esp32-firebase-48836',
    databaseURL:
        'https://esp32-firebase-48836-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-firebase-48836.appspot.com',
    iosClientId:
        '961625405654-5lankhto02dgm2fflas8g7g1marki2ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.gabusBuild',
  );
}
